spring:
  application:
    name: spring-boot-security
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: true
    open-in-view: false #Close DB Connection for Entire HTTP Request-Response and Open It only When Called and close it directly after service returns output.
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 604800 # 7d
  external:
    auth:
      token-url: https://tenant1.sasserver.demo.sas.com/SASLogon/oauth/token
      client-id: ${SAS_CLIENT_SECRET}
      username: ${SAS_USERNAME}
      password: ${SAS_PASSWORD}
#VALIDATING JSON WEB TOKENS